// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Gn6QAqPFxD9hpvC_QS5zt19u8_uMjFM',
    appId: '1:859840278107:web:2878033556c94ca823597e',
    messagingSenderId: '859840278107',
    projectId: 'devminichat',
    authDomain: 'devminichat.firebaseapp.com',
    storageBucket: 'devminichat.appspot.com',
    measurementId: 'G-XZCF1VGMV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmDJ376c4HObiiBknpBQv6_cIpwexxaSw',
    appId: '1:859840278107:android:21cf27b691f69c3223597e',
    messagingSenderId: '859840278107',
    projectId: 'devminichat',
    storageBucket: 'devminichat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG-3EYdVT8Op5eb9k6skrzu-KF4cud9tw',
    appId: '1:859840278107:ios:f5a4c5608b440c4823597e',
    messagingSenderId: '859840278107',
    projectId: 'devminichat',
    storageBucket: 'devminichat.appspot.com',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG-3EYdVT8Op5eb9k6skrzu-KF4cud9tw',
    appId: '1:859840278107:ios:70d1a480bd2a7bb823597e',
    messagingSenderId: '859840278107',
    projectId: 'devminichat',
    storageBucket: 'devminichat.appspot.com',
    iosBundleId: 'com.example.chats.RunnerTests',
  );
}
